var PrimusDB = {
    "rame": {
        "rsam": "images/fusions/rame/ghostfreak",
        "nori": "images/fusions/rame/fourarms",
        "taki": "images/fusions/rame/diamondhead",
        "bafa": "images/fusions/rame/upchuck",
        "funa": "images/fusions/rame/upgrade",
        "aval": "images/fusions/rame/stinkfly",
        "kenm": "images/fusions/rame/heatblast",
        "bric": "images/fusions/rame/wildmutt",
        "ypet": "images/fusions/rame/blitzwolfer",
        "wjas": "images/fusions/rame/xlr8",
        "ansn": "images/fusions/rame/snareoh",
        "pkmn": "images/fusions/rame/frankenstrike",
        "swor": "images/fusions/rame/cannonbolt",
        "gujh": "images/fusions/rame/greymatter",
        "vaxr": "images/fusions/rame/ripjaws"
    },

    "rsam": {
        "rame": "images/fusions/rsam/wildvine",
        "nori": "images/fusions/rsam/fourarms",
        "taki": "images/fusions/rsam/diamondhead",
        "bafa": "images/fusions/rsam/upchuck",
        "funa": "images/fusions/rsam/upgrade",
        "aval": "images/fusions/rsam/stinkfly",
        "kenm": "images/fusions/rsam/heatblast",
        "bric": "images/fusions/rsam/wildmutt",
        "ypet": "images/fusions/rsam/blitzwolfer",
        "wjas": "images/fusions/rsam/xlr8",
        "ansn": "images/fusions/rsam/snareoh",
        "pkmn": "images/fusions/rsam/frankenstrike",
        "swor": "images/fusions/rsam/cannonbolt",
		"gujh": "images/fusions/rsam/greymatter",
        "vaxr": "images/fusions/rsam/ripjaws"
    },

    "nori": {
        "rame": "images/fusions/nori/wildvine",
        "rsam": "images/fusions/nori/ghostfreak",
        "taki": "images/fusions/nori/diamondhead",
        "bafa": "images/fusions/nori/upchuck",
        "funa": "images/fusions/nori/upgrade",
        "aval": "images/fusions/nori/stinkfly",
        "kenm": "images/fusions/nori/heatblast",
        "bric": "images/fusions/nori/wildmutt",
        "ypet": "images/fusions/nori/blitzwolfer",
        "wjas": "images/fusions/nori/xlr8",
        "ansn": "images/fusions/nori/snareoh",
        "pkmn": "images/fusions/nori/frankenstrike",
        "swor": "images/fusions/nori/cannonbolt",
		"gujh": "images/fusions/nori/greymatter",
        "vaxr": "images/fusions/nori/ripjaws"
    },

    "taki": {
        "rame": "images/fusions/taki/wildvine",
        "rsam": "images/fusions/taki/ghostfreak",
        "nori": "images/fusions/taki/fourarms",
        "bafa": "images/fusions/taki/upchuck",
        "funa": "images/fusions/taki/upgrade",
        "aval": "images/fusions/taki/stinkfly",
        "kenm": "images/fusions/taki/heatblast",
        "bric": "images/fusions/taki/wildmutt",
        "ypet": "images/fusions/taki/blitzwolfer",
        "wjas": "images/fusions/taki/xlr8",
        "ansn": "images/fusions/taki/snareoh",
        "pkmn": "images/fusions/taki/frankenstrike",
        "swor": "images/fusions/taki/cannonbolt",
        "gujh": "images/fusions/taki/greymatter",
        "vaxr": "images/fusions/taki/ripjaws"
    },

    "bafa": {
        "rame": "images/fusions/bafa/wildvine",
        "rsam": "images/fusions/bafa/ghostfreak",
        "nori": "images/fusions/bafa/fourarms",
        "taki": "images/fusions/bafa/diamondhead",
        "funa": "images/fusions/bafa/upgrade",
        "aval": "images/fusions/bafa/stinkfly",
        "kenm": "images/fusions/bafa/heatblast",
        "bric": "images/fusions/bafa/wildmutt",
        "ypet": "images/fusions/bafa/blitzwolfer",
        "wjas": "images/fusions/bafa/xlr8",
        "ansn": "images/fusions/bafa/snareoh",
        "pkmn": "images/fusions/bafa/frankenstrike",
        "swor": "images/fusions/bafa/cannonbolt",
        "gujh": "images/fusions/bafa/greymatter",
        "vaxr": "images/fusions/bafa/ripjaws"
    },

    "funa": {
        "rame": "images/fusions/funa/wildvine",
        "rsam": "images/fusions/funa/ghostfreak",
        "nori": "images/fusions/funa/fourarms",
        "taki": "images/fusions/funa/diamondhead",
        "bafa": "images/fusions/funa/upchuck",
        "aval": "images/fusions/funa/stinkfly",
        "kenm": "images/fusions/funa/heatblast",
        "bric": "images/fusions/funa/wildmutt",
        "ypet": "images/fusions/funa/blitzwolfer",
        "wjas": "images/fusions/funa/xlr8",
        "ansn": "images/fusions/funa/snareoh",
        "pkmn": "images/fusions/funa/frankenstrike",
        "swor": "images/fusions/funa/cannonbolt",
        "gujh": "images/fusions/funa/greymatter",
        "vaxr": "images/fusions/funa/ripjaws"
    },

    "aval": {
        "rame": "images/fusions/aval/wildvine",
        "rsam": "images/fusions/aval/ghostfreak",
        "nori": "images/fusions/aval/fourarms",
        "taki": "images/fusions/aval/diamondhead",
        "bafa": "images/fusions/aval/upchuck",
        "funa": "images/fusions/aval/upgrade",
        "kenm": "images/fusions/aval/heatblast",
        "bric": "images/fusions/aval/wildmutt",
        "ypet": "images/fusions/aval/blitzwolfer",
        "wjas": "images/fusions/aval/xlr8",
        "ansn": "images/fusions/aval/snareoh",
        "pkmn": "images/fusions/aval/frankenstrike",
        "swor": "images/fusions/aval/cannonbolt",
		"gujh": "images/fusions/aval/greymatter",
        "vaxr": "images/fusions/aval/ripjaws"
    },

    "kenm": {
        "rame": "images/fusions/kenm/wildvine",
        "rsam": "images/fusions/kenm/ghostfreak",
        "nori": "images/fusions/kenm/fourarms",
        "taki": "images/fusions/kenm/diamondhead",
        "bafa": "images/fusions/kenm/upchuck",
        "funa": "images/fusions/kenm/upgrade",
        "aval": "images/fusions/kenm/stinkfly",
        "bric": "images/fusions/kenm/wildmutt",
        "ypet": "images/fusions/kenm/blitzwolfer",
        "wjas": "images/fusions/kenm/xlr8",
        "ansn": "images/fusions/kenm/snareoh",
        "pkmn": "images/fusions/kenm/frankenstrike",
        "swor": "images/fusions/kenm/cannonbolt",
		"gujh": "images/fusions/kenm/greymatter",
        "vaxr": "images/fusions/kenm/ripjaws"
    },

    "bric": {
        "rame": "images/fusions/bric/wildvine",
        "rsam": "images/fusions/bric/ghostfreak",
        "nori": "images/fusions/bric/fourarms",
        "taki": "images/fusions/bric/diamondhead",
        "bafa": "images/fusions/bric/upchuck",
        "funa": "images/fusions/bric/upgrade",
        "aval": "images/fusions/bric/stinkfly",
        "kenm": "images/fusions/bric/heatblast",
        "ypet": "images/fusions/bric/blitzwolfer",
        "wjas": "images/fusions/bric/xlr8",
        "ansn": "images/fusions/bric/snareoh",
        "pkmn": "images/fusions/bric/frankenstrike",
        "swor": "images/fusions/bric/cannonbolt",
		"gujh": "images/fusions/bric/greymatter",
        "vaxr": "images/fusions/bric/ripjaws"
    },

    "ypet": {
        "rame": "images/fusions/ypet/wildvine",
        "rsam": "images/fusions/ypet/ghostfreak",
        "nori": "images/fusions/ypet/fourarms",
        "taki": "images/fusions/ypet/diamondhead",
        "bafa": "images/fusions/ypet/upchuck",
        "funa": "images/fusions/ypet/upgrade",
        "aval": "images/fusions/ypet/stinkfly",
        "kenm": "images/fusions/ypet/heatblast",
        "bric": "images/fusions/ypet/wildmutt",
        "wjas": "images/fusions/ypet/xlr8",
        "ansn": "images/fusions/ypet/snareoh",
        "pkmn": "images/fusions/ypet/frankenstrike",
        "swor": "images/fusions/ypet/cannonbolt",
		"gujh": "images/fusions/ypet/greymatter",
        "vaxr": "images/fusions/ypet/ripjaws"
    },

    "wjas": {
        "rame": "images/fusions/wjas/wildvine",
        "rsam": "images/fusions/wjas/ghostfreak",
        "nori": "images/fusions/wjas/fourarms",
        "taki": "images/fusions/wjas/diamondhead",
        "bafa": "images/fusions/wjas/upchuck",
        "funa": "images/fusions/wjas/upgrade",
        "aval": "images/fusions/wjas/stinkfly",
        "kenm": "images/fusions/wjas/heatblast",
        "bric": "images/fusions/wjas/wildmutt",
        "ypet": "images/fusions/wjas/blitzwolfer",
        "ansn": "images/fusions/wjas/snareoh",
        "pkmn": "images/fusions/wjas/frankenstrike",
        "swor": "images/fusions/wjas/cannonbolt",
		"gujh": "images/fusions/wjas/greymatter",
        "vaxr": "images/fusions/wjas/ripjaws"
    },

    "ansn": {
        "rame": "images/fusions/ansn/wildvine",
        "rsam": "images/fusions/ansn/ghostfreak",
        "nori": "images/fusions/ansn/fourarms",
        "taki": "images/fusions/ansn/diamondhead",
        "bafa": "images/fusions/ansn/upchuck",
        "funa": "images/fusions/ansn/upgrade",
        "aval": "images/fusions/ansn/stinkfly",
        "kenm": "images/fusions/ansn/heatblast",
        "bric": "images/fusions/ansn/wildmutt",
        "ypet": "images/fusions/ansn/blitzwolfer",
        "wjas": "images/fusions/ansn/xlr8",
        "pkmn": "images/fusions/ansn/frankenstrike",
        "swor": "images/fusions/ansn/cannonbolt",
        "gujh": "images/fusions/ansn/greymatter",
        "vaxr": "images/fusions/ansn/ripjaws"
    },

    "pkmn": {
        "rame": "images/fusions/pkmn/wildvine",
        "rsam": "images/fusions/pkmn/ghostfreak",
        "nori": "images/fusions/pkmn/fourarms",
        "taki": "images/fusions/pkmn/diamondhead",
        "bafa": "images/fusions/pkmn/upchuck",
        "funa": "images/fusions/pkmn/upgrade",
        "aval": "images/fusions/pkmn/stinkfly",
        "kenm": "images/fusions/pkmn/heatblast",
        "bric": "images/fusions/pkmn/wildmutt",
        "ypet": "images/fusions/pkmn/blitzwolfer",
        "wjas": "images/fusions/pkmn/xlr8",
        "ansn": "images/fusions/pkmn/snareoh",
        "swor": "images/fusions/pkmn/cannonbolt",
        "gujh": "images/fusions/pkmn/greymatter",
        "vaxr": "images/fusions/pkmn/ripjaws"
    },

    "swor": {
        "rame": "images/fusions/swor/wildvine",
        "rsam": "images/fusions/swor/ghostfreak",
        "nori": "images/fusions/swor/fourarms",
        "taki": "images/fusions/swor/diamondhead",
        "bafa": "images/fusions/swor/upchuck",
        "funa": "images/fusions/swor/upgrade",
        "aval": "images/fusions/swor/stinkfly",
        "kenm": "images/fusions/swor/heatblast",
        "bric": "images/fusions/swor/wildmutt",
        "ypet": "images/fusions/swor/blitzwolfer",
        "wjas": "images/fusions/swor/xlr8",
        "ansn": "images/fusions/swor/snareoh",
        "pkmn": "images/fusions/swor/frankenstrike",
        "gujh": "images/fusions/swor/greymatter",
        "vaxr": "images/fusions/swor/ripjaws"
    },

    "gujh": {
        "rame": "images/fusions/gujh/wildvine",
        "bafa": "images/fusions/gujh/upchuck",
        "ansn": "images/fusions/gujh/snareoh",
        "pkmn": "images/fusions/gujh/frankenstrike",
        "taki": "images/fusions/gujh/diamondhead",
        "swor": "images/fusions/gujh/cannonbolt",
        "funa": "images/fusions/gujh/upgrade",
		"wjas": "images/fusions/gujh/xlr8",
		"kenm": "images/fusions/gujh/heatblast",
		"bric": "images/fusions/gujh/wildmutt",
		"ypet": "images/fusions/gujh/blitzwolfer",
		"nori": "images/fusions/gujh/fourarms",
		"rsam": "images/fusions/gujh/ghostfreak",
		"aval": "images/fusions/gujh/stinkfly",
        "vaxr": "images/fusions/gujh/ripjaws",
    },

    "vaxr": {
        "rame": "images/fusions/vaxr/wildvine",
        "bafa": "images/fusions/vaxr/upchuck",
        "ansn": "images/fusions/vaxr/snareoh",
        "pkmn": "images/fusions/vaxr/frankenstrike",
        "taki": "images/fusions/vaxr/diamondhead",
        "swor": "images/fusions/vaxr/cannonbolt",
        "funa": "images/fusions/vaxr/upgrade",
		"wjas": "images/fusions/vaxr/xlr8",
		"kenm": "images/fusions/vaxr/heatblast",
		"bric": "images/fusions/vaxr/wildmutt",
		"ypet": "images/fusions/vaxr/blitzwolfer",
		"nori": "images/fusions/vaxr/fourarms",
		"rsam": "images/fusions/vaxr/ghostfreak",
		"aval": "images/fusions/vaxr/stinkfly",
        "gujh": "images/fusions/vaxr/greymatter",
        "unoi": "images/fusions/vaxr/spitter",
    },
    "unoi": {
        "rame": "images/fusions/unoi/wildvine",
        "bafa": "images/fusions/unoi/upchuck",
        "ansn": "images/fusions/unoi/snareoh",
        "pkmn": "images/fusions/unoi/frankenstrike",
        "taki": "images/fusions/unoi/diamondhead",
        "swor": "images/fusions/unoi/cannonbolt",
        "funa": "images/fusions/unoi/upgrade",
		"wjas": "images/fusions/unoi/xlr8",
		"kenm": "images/fusions/unoi/heatblast",
		"bric": "images/fusions/unoi/wildmutt",
		"ypet": "images/fusions/unoi/blitzwolfer",
		"nori": "images/fusions/unoi/fourarms",
		"rsam": "images/fusions/unoi/ghostfreak",
		"aval": "images/fusions/unoi/stinkfly",
        "gujh": "images/fusions/unoi/greymatter",
        "vaxr": "images/fusions/unoi/ripjaws",
    },

    "mura": {
        "mura": "images/fusions/special/gwen",
    },

    "akec": {
        "akec": "images/fusions/special/vilgax",
    },
}